INSERT INTO ACCOUNT(NUMBER, BALANCE) VALUES('1111', 500);
INSERT INTO ACCOUNT(NUMBER, BALANCE) VALUES('1112', 1000);

INSERT INTO TRANSFER(FROM_ACC, TO_ACC, AMOUNT) VALUES(1, 2, 200);
INSERT INTO TRANSFER(FROM_ACC, TO_ACC, AMOUNT) VALUES(1, 2, 200);
INSERT INTO TRANSFER(FROM_ACC, TO_ACC, AMOUNT) VALUES(2, 1, 500);
